server:
  port: 8080

spring:
  application:
    name: device-management-service
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/qct_devices}
    username: ${DATABASE_USERNAME:qct_user}
    password: ${DATABASE_PASSWORD:qct_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 2000ms

logging:
  level:
    com.qct: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/qct_devices
    username: ${DATABASE_USERNAME:qct_user}
    password: ${DATABASE_PASSWORD:qct_password}
  redis:
    host: redis